# Generated by Django 3.2.18 on 2023-04-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_instructor_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='bio',
        ),
        migrations.AddField(
            model_name='instructor',
            name='experience',
            field=models.CharField(default='No experience listed', max_length=50),
        ),
        migrations.AddField(
            model_name='instructor',
            name='specialization',
            field=models.CharField(default='No specialization listed', max_length=50),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
