# Generated by Django 3.2.18 on 2023-04-26 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20230425_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.instructor'),
            preserve_default=False,
        ),
    ]
